export const cart = {
    ADD_PEOPLE_ITEM_TO_CART: 'ADD_PEOPLE_ITEM_TO_CART',
    ADD_STAR_SHIP_ITEM_TO_CART: 'ADD_STAR_SHIP_ITEM_TO_CART',

    ADD_DATA_TO_CART_FROM_LOCAL_STORAGE: 'ADD_DATA_TO_CART_FROM_LOCAL_STORAGE',

    ADD_PEOPLE_ITEMS_FROM_LOCAL_STORAGE: 'ADD_PEOPLE_ITEMS_FROM_LOCAL_STORAGE',
    ADD_STAR_SHIP_ITEMS_FROM_LOCAL_STORAGE: 'ADD_STAR_SHIP_ITEMS_FROM_LOCAL_STORAGE',

    PLUS_ONE_PEOPLE_TO_CART: 'PLUS_ONE_PEOPLE_TO_CART',
    MINUS_ONE_PEOPLE_FROM_CART: 'MINUS_ONE_PEOPLE_FROM_CART',
    PLUS_ONE_STAR_SHIP_TO_CART: 'PLUS_ONE_STAR_SHIP_TO_CART',
    MINUS_ONE_STAR_SHIP_FROM_CART: 'MINUS_ONE_STAR_SHIP_FROM_CART',

    CLEAR_ONE_PEOPLE_ITEM_CART: 'CLEAR_ONE_PEOPLE_ITEM_CART',
    CLEAR_ONE_STAR_SHIP_ITEM_CART: 'CLEAR_ONE_STAR_SHIP_ITEM_CART',

    CLEAR_CART: 'CLEAR_CART'
}