export const config = {
    SET_DEFAULT_CATEGORIES: 'SET_DEFAULT_CATEGORIES',
    ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    RENAME_CATEGORY: 'RENAME_CATEGORY'

}