export const interim = {
    INTERIM_NEW_CATEGORY: 'INTERIM_NEW_CATEGORY',
    INTERIM_CLEAR_NEW_CATEGORY: 'INTERIM_CLEAR_NEW_CATEGORY',

    INTERIM_DELETE_CATEGORY: 'INTERIM_DELETE_CATEGORY',
    INTERIM_CLEAR_DELETED_CATEGORY: 'INTERIM_CLEAR_DELETED_CATEGORY'
}