export const interim = {
    INTERIM_NEW_CATEGORY: 'INTERIM_NEW_CATEGORY',
    INTERIM_REMOVE_NEW_CATEGORY: 'INTERIM_REMOVE_NEW_CATEGORY',

    INTERIM_DELETE_CATEGORY: 'INTERIM_DELETE_CATEGORY',
    INTERIM_REMOVE_DELETED_CATEGORY: 'INTERIM_REMOVE_DELETED_CATEGORY',

    INTERIM_RENAMED_CATEGORY:'INTERIM_RENAMED_CATEGORY',
    INTERIM_REMOVE_RENAMED_CATEGORY:'INTERIM_REMOVE_RENAMED_CATEGORY'
}