export const people = {
    GET_ALL_PEOPLE_SUCСESS: 'GET_ALL_PEOPLE_SUCСESS',
    GET_ALL_PEOPLE_FAILED: 'GET_ALL_PEOPLE_FAILED',
    GET_ALL_PEOPLE_PENDING: 'GET_ALL_PEOPLE_PENDING',

    GET_ONE_PEOPLE_SUCСESS: 'GET_ONE_PEOPLE_SUCСESS',
    GET_ONE_PEOPLE_FAILED: 'GET_ONE_PEOPLE_FAILED',
    GET_ONE_PEOPLE_PENDING: 'GET_ONE_PEOPLE_PENDING',
}