export const starships = {
    GET_ALL_STAR_SHIPS_SUCСESS: 'GET_ALL_STAR_SHIPS_SUCСESS',
    GET_ALL_STAR_SHIPS_FAILED: 'GET_ALL_STAR_SHIPS_FAILED',
    GET_ALL_STAR_SHIPS_PENDING: 'GET_ALL_STAR_SHIPS_PENDING',

    GET_ONE_STAR_SHIP_SUCСESS: 'GET_ONE_STAR_SHIP_SUCСESS',
    GET_ONE_STAR_SHIP_FAILED: 'GET_ONE_STAR_SHIP_FAILED',
    GET_ONE_STAR_SHIP_PENDING: 'GET_ONE_STAR_SHIP_PENDING',
}

