export const states = {
    TOGGLE_POPUP: 'TOGGLE_POPUP',
    TOGGLE_EDIT_CATEGORY: 'TOGGLE_EDIT_CATEGORY',
    TOGGLE_RENAME_CATEGORY: 'TOGGLE_RENAME_CATEGORY',
    TOGGLE_ADD_CATEGORY: 'TOGGLE_ADD_CATEGORY',
    TOGGLE_SAVE_CATEGORY: 'TOGGLE_SAVE_CATEGORY',
}