export const categoryConfig = [
    { id: 1, name: 'Twitter' },
    { id: 2, name: 'LinkedIn' },
    { id: 3, name: 'WhatsApp' },
    { id: 4, name: 'Telegram' },
    { id: 5, name: 'Vk' },
    { id: 6, name: 'Meta' },
    { id: 7, name: 'Clubhouse' },
    { id: 8, name: 'YouTube' },
    { id: 9, name: 'Facebook' },
    { id: 10, name: 'GitHub' },
    { id: 11, name: 'Instagram' },
    { id: 1, name: 'Twitter' },
    { id: 2, name: 'LinkedIn' },
    { id: 3, name: 'WhatsApp' },
    { id: 4, name: 'Telegram' },
    { id: 5, name: 'Vk' },
    { id: 6, name: 'Meta' },
    { id: 7, name: 'Clubhouse' },
    { id: 8, name: 'YouTube' },
    { id: 9, name: 'Facebook' },
    { id: 10, name: 'GitHub' },
    { id: 11, name: 'Instagram' },
]